server:
  port: 8881
  session.timeout: 60000
  servlet.contextpath: /cloudDisk

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format-sql: true #JPA打印SQL日志格式化输出配置项
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB #单个请求最大大小
swagger:
  enabled: true

hdfs:
  path: hdfs://node1:9000
  username: root

logging:
  level:
    root: warn
    org.springframework: warn
    com.project: info
  file:
    path: ./logs
    name: cloudDisk.log

